# Generated by Django 2.1.3 on 2019-05-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomruta', models.CharField(max_length=200)),
                ('descripcio', models.CharField(max_length=500)),
                ('distancia_km', models.IntegerField()),
                ('dificultat', models.IntegerField()),
            ],
        ),
    ]
